# Generated by Django 6.0.8 on 2026-08-05 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='ulr_imagem',
            new_name='ulr_imagen',
        ),
    ]
