# Generated by Django 6.0.8 on 2026-08-05 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_rename_ulr_imagem_news_ulr_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='ulr_imagen',
            new_name='url_imagen',
        ),
    ]
