# Generated by Django 6.0.8 on 2026-08-06 00:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_rename_ulr_imagen_news_url_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='data_criacao',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='show',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='titulo',
            field=models.CharField(blank=True, default='Sem Titulo', max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='url_imagen',
            field=models.CharField(blank=True, default='Sem url da imagem', max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='url_noticia',
            field=models.CharField(blank=True, default='Sem url da noticia', max_length=255),
        ),
    ]
