# Generated by Django 6.0.8 on 2026-08-06 00:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_alter_news_data_criacao_alter_news_show_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='news',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='url_imagen',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='url_noticia',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
