# Generated by Django 6.0.8 on 2026-08-15 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_alter_news_data_criacao_alter_news_show_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='url_imagen',
            new_name='url_imagem',
        ),
    ]
